name: uploader

on:
  release:
    types: [deleted]
  workflow_dispatch:

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
  
jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV

    - name: remove tag
      if: ${{github.event_name == 'release' && github.event.action == 'deleted'}}
      uses: dev-drprasad/delete-tag-and-release@v1.0
      with:
        delete_release: true
        tag_name: ${{ env.RELEASE_VERSION }}
        repo: kLauncher/kLauncher
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


