name: uploader

on:
  release:
    types: [released, edited, deleted]

  workflow_dispatch:

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
  
jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f ./data/requirements.txt ]; then pip install -r ./data/requirements.txt; fi

    - name: run script
      env:
        LAUNCHER_URL: ${{ secrets.LAUNCHER_URL }}
        LAUNCHER_KEY: ${{ secrets.LAUNCHER_KEY }}
        VERSION: ${{ env.RELEASE_VERSION }}
        ACTION: ${{ github.event.action }}
        ABCD: ${{ secrets.ABCD }}
      run: python ./data/upload.py

    - name: remove tag
      if: ${{github.event_name == 'release' && github.event.action == 'deleted'}}
      uses: dev-drprasad/delete-tag-and-release@v1.0
      with:
        delete_release: true
        tag_name: ${{ env.RELEASE_VERSION }}
        repo: kLauncher/kLauncher
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


